_wandb:
    value:
        cli_version: 0.21.1
        e:
            vu4iqnuw0jkqisxvj9rc3v5yn3gj5v0n:
                args:
                    - --sweep
                codePath: wandb_minimize_sum_laps.py
                codePathLocal: wandb_minimize_sum_laps.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "501809635328"
                        used: "106783522816"
                email: nakanishi.shuntaro.638@s.kyushu-u.ac.jp
                executable: /home/ubuntu/aichallenge-2025/.venv/bin/python
                git:
                    commit: b80fd8687b73fd667a6a122a99cb4f592f3085be
                    remote: git@github.com:NakanishiShuntaro/aichallenge-2025.git
                host: ubuntu-HP-Laptop-14s-dq5xxx
                memory:
                    total: "16425721856"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /home/ubuntu/aichallenge-2025/wandb_minimize_sum_laps.py
                python: CPython 3.13.6
                root: /home/ubuntu/aichallenge-2025
                startedAt: "2025-08-10T16:26:50.100473Z"
                writerId: vu4iqnuw0jkqisxvj9rc3v5yn3gj5v0n
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.6
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
accel_lowpass_gain:
    value: 0.28036610850755495
extend_state_step:
    value: 192
external_target_vel:
    value: 14.553949600432826
lookahead_gain:
    value: 0.6197456913005122
lookahead_min_distance:
    value: 4.531424016533091
pose_additional_delay_var:
    value: 0.5189364542973902
pose_smoothing_steps:
    value: 1
proc_stddev_vx_c:
    value: 16.09147850801435
proc_stddev_wz_c:
    value: 0.8729857260552925
speed_proportional_gain:
    value: 1.1148265261406058
steering_tire_angle_gain_var:
    value: 1.589577406201817
stop_hold_sec:
    value: 20
stop_threshold:
    value: 0.1974865627978062
tf_rate:
    value: 42.29550188847805
twist_smoothing_steps:
    value: 1
