_wandb:
    value:
        cli_version: 0.21.1
        e:
            3ubeag1u5alknhhyobaqfdomr0c7ip1a:
                args:
                    - --sweep
                codePath: wandb_minimize_sum_laps.py
                codePathLocal: wandb_minimize_sum_laps.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "501809635328"
                        used: "88617463808"
                email: nakanishi.shuntaro.638@s.kyushu-u.ac.jp
                executable: /home/ubuntu/aichallenge-2025/.venv/bin/python
                git:
                    commit: 3040f926eb966b3b837d9b935a06090907bff5d5
                    remote: git@github.com:NakanishiShuntaro/aichallenge-2025.git
                host: ubuntu-HP-Laptop-14s-dq5xxx
                memory:
                    total: "16425721856"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /home/ubuntu/aichallenge-2025/wandb_minimize_sum_laps.py
                python: CPython 3.13.6
                root: /home/ubuntu/aichallenge-2025
                startedAt: "2025-08-10T13:21:12.284107Z"
                writerId: 3ubeag1u5alknhhyobaqfdomr0c7ip1a
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.6
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
accel_lowpass_gain:
    value: 0.7524696916794414
extend_state_step:
    value: 189
external_target_vel:
    value: 15.744595070261914
lookahead_gain:
    value: 0.9411425056514022
lookahead_min_distance:
    value: 4.3934009822777345
pose_additional_delay_var:
    value: 0.7456748683917885
pose_smoothing_steps:
    value: 4
proc_stddev_vx_c:
    value: 24.839934844309177
proc_stddev_wz_c:
    value: 2.2788986681870735
speed_proportional_gain:
    value: 1.027749877642821
steering_tire_angle_gain_var:
    value: 1.1340223088412074
stop_hold_sec:
    value: 16
stop_threshold:
    value: 0.07132474096400533
tf_rate:
    value: 27.638795428646844
twist_smoothing_steps:
    value: 5
