_wandb:
    value:
        cli_version: 0.21.1
        e:
            04dfakrv96oe0pidknsvct0lr6uab7q7:
                args:
                    - --sweep
                codePath: wandb_minimize_sum_laps.py
                codePathLocal: wandb_minimize_sum_laps.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "501809635328"
                        used: "76426366976"
                email: nakanishi.shuntaro.638@s.kyushu-u.ac.jp
                executable: /home/ubuntu/aichallenge-2025/.venv/bin/python
                git:
                    commit: fdcf156659e8879d0d522de3d1c245f8ad21d91a
                    remote: git@github.com:NakanishiShuntaro/aichallenge-2025.git
                host: ubuntu-HP-Laptop-14s-dq5xxx
                memory:
                    total: "16425717760"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /home/ubuntu/aichallenge-2025/wandb_minimize_sum_laps.py
                python: CPython 3.13.6
                root: /home/ubuntu/aichallenge-2025
                startedAt: "2025-08-10T08:02:27.730665Z"
                writerId: 04dfakrv96oe0pidknsvct0lr6uab7q7
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.6
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
accel_lowpass_gain:
    value: 0.12677658139436712
extend_state_step:
    value: 108
external_target_vel:
    value: 13.438854669799053
lookahead_gain:
    value: 0.761136217158604
lookahead_min_distance:
    value: 4.463811622549355
pose_additional_delay_var:
    value: 0.8426729968530793
pose_smoothing_steps:
    value: 4
proc_stddev_vx_c:
    value: 23.557379112828855
proc_stddev_wz_c:
    value: 1.310201296774545
speed_proportional_gain:
    value: 0.672076360414693
steering_tire_angle_gain_var:
    value: 1.2204348154686744
stop_hold_sec:
    value: 6
stop_threshold:
    value: 0.07697862308387939
tf_rate:
    value: 43.17824305283074
twist_smoothing_steps:
    value: 3
