_wandb:
    value:
        cli_version: 0.21.1
        e:
            w18k2z8xw37xv717xd862w97wurdldoy:
                args:
                    - --sweep
                codePath: wandb_minimize_sum_laps.py
                codePathLocal: wandb_minimize_sum_laps.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "501809635328"
                        used: "64846143488"
                email: nakanishi.shuntaro.638@s.kyushu-u.ac.jp
                executable: /home/ubuntu/aichallenge-2025/.venv/bin/python
                git:
                    commit: 3376fc59052a43279a83ee444616001b50b03387
                    remote: git@github.com:NakanishiShuntaro/aichallenge-2025.git
                host: ubuntu-HP-Laptop-14s-dq5xxx
                memory:
                    total: "16425717760"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /home/ubuntu/aichallenge-2025/wandb_minimize_sum_laps.py
                python: CPython 3.13.6
                root: /home/ubuntu/aichallenge-2025
                startedAt: "2025-08-10T03:35:22.604534Z"
                writerId: w18k2z8xw37xv717xd862w97wurdldoy
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.6
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
accel_lowpass_gain:
    value: 0.948100306872924
extend_state_step:
    value: 106
external_target_vel:
    value: 29.63269136398383
lookahead_gain:
    value: 0.8317341923963657
lookahead_min_distance:
    value: 2.9477675595740775
pose_additional_delay_var:
    value: 0.4619921482928854
pose_smoothing_steps:
    value: 3
proc_stddev_vx_c:
    value: 23.71106269398734
proc_stddev_wz_c:
    value: 1.5586980158487844
speed_proportional_gain:
    value: 2.8911682957646927
steering_tire_angle_gain_var:
    value: 1.2764800638365288
stop_hold_sec:
    value: 19
stop_threshold:
    value: 0.14503920646436297
tf_rate:
    value: 40.2053047699562
twist_smoothing_steps:
    value: 3
