_wandb:
    value:
        cli_version: 0.21.1
        e:
            ro2jo5yi6n4e8saej9nrzbojxhj7u1fg:
                args:
                    - --sweep
                codePath: wandb_minimize_sum_laps.py
                codePathLocal: wandb_minimize_sum_laps.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "501809635328"
                        used: "88096890880"
                email: nakanishi.shuntaro.638@s.kyushu-u.ac.jp
                executable: /home/ubuntu/aichallenge-2025/.venv/bin/python
                git:
                    commit: 5eeeff8fdfdbde6127f35c8b529c4b8243d5a8ba
                    remote: git@github.com:NakanishiShuntaro/aichallenge-2025.git
                host: ubuntu-HP-Laptop-14s-dq5xxx
                memory:
                    total: "16425721856"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /home/ubuntu/aichallenge-2025/wandb_minimize_sum_laps.py
                python: CPython 3.13.6
                root: /home/ubuntu/aichallenge-2025
                startedAt: "2025-08-10T13:02:57.203598Z"
                writerId: ro2jo5yi6n4e8saej9nrzbojxhj7u1fg
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.6
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
accel_lowpass_gain:
    value: 0.19187940391761155
extend_state_step:
    value: 75
external_target_vel:
    value: 10.071730089454263
lookahead_gain:
    value: 0.760682653238031
lookahead_min_distance:
    value: 3.542162004925409
pose_additional_delay_var:
    value: 0.7558098311373515
pose_smoothing_steps:
    value: 4
proc_stddev_vx_c:
    value: 19.52717208412399
proc_stddev_wz_c:
    value: 2.331262216464184
speed_proportional_gain:
    value: 2.612498833969905
steering_tire_angle_gain_var:
    value: 1.2631635372433525
stop_hold_sec:
    value: 25
stop_threshold:
    value: 0.11212370136577612
tf_rate:
    value: 11.319061066518232
twist_smoothing_steps:
    value: 1
